language: r
sudo: required
cache: packages

services:
  - docker

r_build_args: '--no-build-vignettes'
r_check_args: '--no-vignettes'

r:
 - 3.2
 - 3.3
 - 3.4
 - 3.5
 - 3.6
 - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
